// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace bscApi.Models;

public partial class bscContext : DbContext
{
    public bscContext(DbContextOptions<bscContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CatEstatusPedido> CatEstatusPedidos { get; set; }

    public virtual DbSet<CatEstatusUsuario> CatEstatusUsuarios { get; set; }

    public virtual DbSet<CategoriaProducto> CategoriaProductos { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Pedido> Pedidos { get; set; }

    public virtual DbSet<Perfile> Perfiles { get; set; }

    public virtual DbSet<Persona> Personas { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<ProductoPedido> ProductoPedidos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<VwGetClient> VwGetClients { get; set; }

    public virtual DbSet<VwGetOrder> VwGetOrders { get; set; }

    public virtual DbSet<VwGetProduct> VwGetProducts { get; set; }

    public virtual DbSet<VwGetUser> VwGetUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CatEstatusPedido>(entity =>
        {
            entity.HasKey(e => e.IdEstatusPedidos).HasName("PK__cat_esta__A855B05DAAE10E23");

            entity.ToTable("cat_estatus_pedidos");

            entity.Property(e => e.IdEstatusPedidos).HasColumnName("id_estatus_pedidos");
            entity.Property(e => e.EstatusPedidos)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("estatus_pedidos");
        });

        modelBuilder.Entity<CatEstatusUsuario>(entity =>
        {
            entity.HasKey(e => e.IdEstatusUsuario).HasName("PK__cat_esta__0630AC907EF1331A");

            entity.ToTable("cat_estatus_usuarios");

            entity.Property(e => e.IdEstatusUsuario).HasColumnName("id_estatus_usuario");
            entity.Property(e => e.EstatusUsuarios)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("estatus_usuarios");
        });

        modelBuilder.Entity<CategoriaProducto>(entity =>
        {
            entity.HasKey(e => e.IdCategoriaProducto).HasName("PK__categori__8764350122C41E45");

            entity.ToTable("categoria_productos");

            entity.Property(e => e.IdCategoriaProducto).HasColumnName("id_categoria_producto");
            entity.Property(e => e.CategoriaProducto1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("categoria_producto");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__clientes__677F38F5DF0C0866");

            entity.ToTable("clientes");

            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdPersona)
                .HasConstraintName("FK__clientes__id_per__7C4F7684");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasKey(e => e.IdPedido).HasName("PK__pedidos__6FF01489DEC11958");

            entity.ToTable("pedidos");

            entity.Property(e => e.IdPedido).HasColumnName("id_pedido");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdEstatusPedido).HasColumnName("id_estatus_pedido");
            entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");
            entity.Property(e => e.PrecioTotal)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_total");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Pedidos)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("FK__pedidos__id_clie__04E4BC85");

            entity.HasOne(d => d.IdEstatusPedidoNavigation).WithMany(p => p.Pedidos)
                .HasForeignKey(d => d.IdEstatusPedido)
                .HasConstraintName("FK__pedidos__id_esta__05D8E0BE");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Pedidos)
                .HasForeignKey(d => d.IdUsuario)
                .HasConstraintName("FK__pedidos__id_usua__03F0984C");
        });

        modelBuilder.Entity<Perfile>(entity =>
        {
            entity.HasKey(e => e.IdPerfil).HasName("PK__perfiles__1D1C8768FBFE4234");

            entity.ToTable("perfiles");

            entity.Property(e => e.IdPerfil).HasColumnName("id_perfil");
            entity.Property(e => e.Perfil)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("perfil");
        });

        modelBuilder.Entity<Persona>(entity =>
        {
            entity.HasKey(e => e.IdPersona).HasName("PK__persona__228148B03162CC94");

            entity.ToTable("persona");

            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.AMaterno)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("a_materno");
            entity.Property(e => e.APaterno)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("a_paterno");
            entity.Property(e => e.Contrasenia)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("contrasenia");
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("correo");
            entity.Property(e => e.Domicilio)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("domicilio");
            entity.Property(e => e.FCreacion)
                .HasColumnType("datetime")
                .HasColumnName("f_creacion");
            entity.Property(e => e.FModifico)
                .HasColumnType("datetime")
                .HasColumnName("f_modifico");
            entity.Property(e => e.FNacimiento)
                .HasColumnType("datetime")
                .HasColumnName("f_nacimiento");
            entity.Property(e => e.Nombre)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("telefono");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.IdProducto).HasName("PK__producto__FF341C0D287FDE16");

            entity.ToTable("productos");

            entity.Property(e => e.IdProducto).HasColumnName("id_producto");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.IdCategoriaProducto).HasColumnName("id_categoria_producto");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");
            entity.Property(e => e.Producto1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("producto");

            entity.HasOne(d => d.IdCategoriaProductoNavigation).WithMany(p => p.Productos)
                .HasForeignKey(d => d.IdCategoriaProducto)
                .HasConstraintName("FK__productos__id_ca__778AC167");
        });

        modelBuilder.Entity<ProductoPedido>(entity =>
        {
            entity.HasKey(e => e.IdProductoPedido).HasName("PK__producto__878B1FAF1A94BFE4");

            entity.ToTable("producto_pedido");

            entity.Property(e => e.IdProductoPedido).HasColumnName("id_producto_pedido");
            entity.Property(e => e.IdPedido).HasColumnName("id_pedido");
            entity.Property(e => e.IdProducto).HasColumnName("id_producto");

            entity.HasOne(d => d.IdPedidoNavigation).WithMany(p => p.ProductoPedidos)
                .HasForeignKey(d => d.IdPedido)
                .HasConstraintName("FK__producto___id_pe__09A971A2");

            entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.ProductoPedidos)
                .HasForeignKey(d => d.IdProducto)
                .HasConstraintName("FK__producto___id_pr__08B54D69");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__usuarios__4E3E04AD839F5CA7");

            entity.ToTable("usuarios");

            entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");
            entity.Property(e => e.IdEstatusUsuario).HasColumnName("id_estatus_usuario");
            entity.Property(e => e.IdPerfil).HasColumnName("id_perfil");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");

            entity.HasOne(d => d.IdEstatusUsuarioNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdEstatusUsuario)
                .HasConstraintName("FK__usuarios__id_est__01142BA1");

            entity.HasOne(d => d.IdPerfilNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdPerfil)
                .HasConstraintName("FK__usuarios__id_per__00200768");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.IdPersona)
                .HasConstraintName("FK__usuarios__id_per__7F2BE32F");
        });

        modelBuilder.Entity<VwGetClient>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VwGetClients");

            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.NombreCompleto)
                .IsRequired()
                .HasMaxLength(302)
                .IsUnicode(false)
                .HasColumnName("nombre_completo");
        });

        modelBuilder.Entity<VwGetOrder>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VwGetOrders");

            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.EstatusPedidos)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("estatus_pedidos");
            entity.Property(e => e.IdEstatusPedidos).HasColumnName("id_estatus_pedidos");
            entity.Property(e => e.IdPedido).HasColumnName("id_pedido");
            entity.Property(e => e.PrecioTotal)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio_total");
        });

        modelBuilder.Entity<VwGetProduct>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VwGetProducts");

            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.CategoriaProducto)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("categoria_producto");
            entity.Property(e => e.IdCategoriaProducto).HasColumnName("id_categoria_producto");
            entity.Property(e => e.IdProducto).HasColumnName("id_producto");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");
            entity.Property(e => e.Producto)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("producto");
        });

        modelBuilder.Entity<VwGetUser>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("VwGetUsers");

            entity.Property(e => e.AMaterno)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("a_materno");
            entity.Property(e => e.APaterno)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("a_paterno");
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("correo");
            entity.Property(e => e.Domicilio)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("domicilio");
            entity.Property(e => e.EstatusUsuario)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("estatus_usuario");
            entity.Property(e => e.FNacimiento)
                .HasColumnType("datetime")
                .HasColumnName("f_nacimiento");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.Nombre)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.NombrePerfil).HasColumnName("nombre_perfil");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("telefono");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}