// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bscApi.Models;

public partial class CatEstatusUsuario
{
    public int IdEstatusUsuario { get; set; }

    public string EstatusUsuarios { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}