// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bscApi.Models;

public partial class CategoriaProducto
{
    public int IdCategoriaProducto { get; set; }

    public string CategoriaProducto1 { get; set; }

    public virtual ICollection<Producto> Productos { get; set; } = new List<Producto>();
}