// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bscApi.Models;

public partial class CatEstatusPedido
{
    public int IdEstatusPedidos { get; set; }

    public string EstatusPedidos { get; set; }

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();
}