// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bscApi.Models;

public partial class VwGetUser
{
    public int IdPersona { get; set; }

    public string Nombre { get; set; }

    public string APaterno { get; set; }

    public string AMaterno { get; set; }

    public string Domicilio { get; set; }

    public string Telefono { get; set; }

    public DateTime? FNacimiento { get; set; }

    public string Correo { get; set; }

    public int NombrePerfil { get; set; }

    public string EstatusUsuario { get; set; }
}