// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bscApi.Models;

public partial class VwGetClient
{
    public int IdPersona { get; set; }

    public int IdCliente { get; set; }

    public string NombreCompleto { get; set; }
}