// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bscApi.Models;

public partial class VwGetProduct
{
    public int IdProducto { get; set; }

    public int? IdCategoriaProducto { get; set; }

    public string Producto { get; set; }

    public decimal? Precio { get; set; }

    public int? Cantidad { get; set; }

    public string CategoriaProducto { get; set; }
}