// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bscApi.Models;

public partial class VwGetOrder
{
    public int IdPedido { get; set; }

    public int IdEstatusPedidos { get; set; }

    public string EstatusPedidos { get; set; }

    public int? Cantidad { get; set; }

    public decimal? PrecioTotal { get; set; }
}